services:
  db:
    image: mysql:8.4
    ports:
      - '3306:3306' # ホスト側:コンテナ側のポート番号
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 3

  web:
    build:
      context: .
      # 開発用のDockerfileを指定
      dockerfile: Dockerfile.dev
      # args: # 必要に応じてビルド時引数を設定
      #   RAILS_ENV: development
    # デバック用　３０００番ポートなら直接railsにアクセスできる
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig:ro
    environment:
      #　開発用の環境変数を指定
      RAILS_ENV: development
      NODE_ENV: development
      # Dockerfile側の本番用設定を上書きし、全Gemをインストール
      BUNDLE_WITHOUT: ''
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    tty: true # ウォッチャープロセスのために必要

  # Nginxサービスを追加
  nginx:
    # イメージはローカルファイルを指定しないに変更、公式イメージを使用

    image: nginx:stable-alpine
    # build:
    #   context: ./nginx
    # HTTP通信用の標準ポートである80番で通信をローカルで受けて、このコンテナの80番ポートに転送、nginx.confへ
    ports:
      - '80:80'
    volumes:
      # ローカル開発用のNginx設定ファイルをコンテナ内のNginxが読み込む場所にマウント
      # コロンのホスト側のパス : コンテナ側のパス [:オプション]
      - ./nginx/nginx.conf.local:/etc/nginx/conf.d/default.conf
        #/app/public: Nginxコンテナ内の指定パス　、ここからローカルにあるpublicディレクトリを参照
      - ./public:/app/public #
    # Railsアプリが起動してから、Nginxが起動する順序を保証
    # proxy_pass http://web:3000の設定がエラーにならないためにはrailsが起動している必要がある
    depends_on:
      - web
volumes:
  mysql_data:
