

# sendfile on;
# tcp_nopush on;
# tcp_nodelay on;
# keepalive_timeout 65;
client_max_body_size 20M; # アプリケーション全体でのリクエストボディサイズ上限

server {
    # ポート80でHTTPリクエストを受け付け
    listen 80;
    # ALBは既にドメイン名に基づいたルーティング済、server_name をチェックし不要、リクエストは全てこの server ブロックで受ける
    server_name _;

    # Nginxのログフォーマットを定義
    access_log /dev/stdout main; # 'main' は上記で定義済み
    error_log /dev/stderr warn;  # エラーレベルをwarnにするとで情報量を調整

    # serverブロックのファイルの基本的な置き場所を以下で指定
    root /app/public; # Railsアプリケーションの public ディレクトリ

    # 特定のURLパターンに対するnginxの処理方法を定義 (静的アセット)
    location ~ ^/(assets|packs|images|javascripts|stylesheets|system|builds|css|js)/ {
        # 検索場所は上記で指定した/publicディレクトリ
        # ファイルが見つからなければ404
        try_files $uri $uri/ =404;
        # 高速化のためアクセスログをオフ
        access_log off;
        # キャッシュの有効期限を設定
        expires max;
        # ブラウザやCDNに積極的にキャッシュさせる
        add_header Cache-Control public;
        # Railsがプリコンパイル時に.gzファイルも生成していた場合はnginxがそれを返す
        gzip_static on;
    }

    # 静的ファイルとして処理されなかったリクエスト以外をRailsアプリケーション (webサービス) に渡す
    location / {
        # proxy_pass ディレクティブで、リクエストを転送する先のサービス名を指定します。
        # docker-compose.yml で定義したRailsアプリケーションのサービス名は 'web' でしたので、
        # 'web:3000' となります (ポート3000でリッスンしていると仮定)。
        proxy_pass http://web:3000;

        # リクエストHostヘッダを確実にRailsに渡す、空文字列の場合はエラーになる
        proxy_set_header Host $http_host;
        # Nginx に直接接続してきたクライアントの IP アドレス
        # これがないとRailsのログにNginxのIPアドレスが記録される
        proxy_set_header X-Real-IP $remote_addr;
        # Nginxがプロキシサーバーとして動作していることをRailsに伝える
        # $proxy_add_x_forwarded_for は既存の X-Forwarded-For ヘッダに $remote_addr を追加します
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # リクエストが HTTP か HTTPSかを伝える。ALBからのリクエストはHTTPだが大元のリクエストがHTTPS予定
        # $scheme は現在の接続のスキーム (http または https)
        proxy_set_header X-Forwarded-Proto $scheme;
        # 元のリクエストのHostヘッダー
        proxy_set_header X-Forwarded-Host $http_host;
        # 元のリクエストのポート (この場合はALBが受けたポート)
        proxy_set_header X-Forwarded-Port $server_port;

        # プロキシのタイムアウト設定
        # Nginxからバックエンドサーバーへの接続確立時のタイムアウト値　回線遅延を考慮して長めに設定
        proxy_connect_timeout 60s;
        # データ送信時
        proxy_send_timeout   60s;
        # データ受信時
        proxy_read_timeout   60s;
    }
}